#!/bin/bash
<<Doc
Name: Jagadeesh
Date: 28-09-2022
Description: Write a script to determine whether a given file system or mount point is mounted
Sample i/p: ./mounted_fs.sh /dev/sda2
Sample o/p: File-system /dev/sda2 is mounted on / and it is having 98%
	        Used space with 3298220 KB free.
Doc
flag=0				                                                        	# initialize the flag
filespace=(`df | tr –s " " | cut –d " " -f1`)		                            # storing the filespace to filespace array
mount=(`df | tr -s " " | cut -d " " -f6`)	                                	# storing the mount to mount array
use=(`df | tr -s " " | cut -d " " -f5`)		                                    # storing the used space to use array
availspace=(`dr | tr -s " " | cut " " -f4`)		                                # Storing the available space to availspace
length=${#filespace[@]}				                                            # storing the length of an array in length
if [ $# -eq 1 ]					                                                # checking the command line argument is one
then
	for in `seq$(($length-1))`		                                            # loop for length -1 times
	do
		if [ $1 = ${filespace[$i]} ]	                                        # check for the same names
		then
		flag=1				                                                    # making flag to one
		echo “File-system $1 is mounted on ${mount[$1]} and it is having ${use[$i]} used space with ${availspace[$i]} KB free.""
		fi
	done
    if [ $flag –eq 0 ]			                                        		# check flag value
    then
	    echo “$1 is not mounted.”	                                        	# if flag value is 0 then filespace is not mount
	fi
else
    echo “Error : Please pass the name of the file-system through command line.”    # error message
else
	echo “”				                                                    	# error message
fi
