#!/bin/bash

<<Doc
Name:Jagadeesh
Date:21-09-2022
Description: Arithmatic caculator using command line arguments 
Sample i/p: 24 + 41 | 10 x 5 | 25 / 5 | 10.2 - 5.6 
Sample o/p: 66 | 50 | 5 | 4.6
Doc

if [ $# -gt 0 ]					            	                # command line argument
then
    if [ $# -eq 3 ]				            	              # check the condition
    then
	case $2 in				                	                # case
	    +) v=`echo "scale=2;$1 $2 $3" | bc`		          # addition
		echo "$1 $2 $3 =$v"
		;;
	    x) v=`echo "scale=2;$1 * $3" | bc`		          # multiplication
	    	echo "$1 x $3 = $v"
		;;
	    /) v=`echo "scale=2;$1 $2 $3" | bc`		          # division
	    	echo "$1 $2 $3 = $v"
		;;
	    -) v=`echo "scale=2;$1 $2 $3" | bc`		          # subtraction
		echo "$1 $2 $3 = $v"
		;;
	esac
else
    echo "Error :Please pass 3 arguments."
    echo "Usage:./arithmatic_calc.sh 2.3 + 6.7"
    fi
else
    echo "Error : Please pass the arguments through command line."
    echo "Usage:./arithmatic_calc.sh 2.3 + 6.7"
fi
